name: GitHub Classroom Workflow

on:
  - push
  - workflow_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Install puppeteer
        run: |
          npm install -g puppeteer
      - uses: actions/checkout@v4
      - uses: GittyBitch/autograding@feature/feedback